# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "cats", :force => true do |t|
    t.column "name",       :string
    t.column "person_id",  :integer
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "dogs", :force => true do |t|
    t.column "name",       :string
    t.column "person_id",  :integer
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "people", :force => true do |t|
    t.column "name",       :string
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

end
