# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "cats", :force => true do |t|
    t.column "name",       :string
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "dogs", :force => true do |t|
    t.column "name",       :string
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "groups", :force => true do |t|
    t.column "name",        :string
    t.column "description", :string
    t.column "permanent",   :boolean,  :default => false
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "created_by",  :integer
    t.column "updated_by",  :integer
  end

  create_table "memberships", :force => true do |t|
    t.column "group_id",   :integer
    t.column "user_id",    :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "created_by", :integer
    t.column "updated_by", :integer
  end

  create_table "permissions", :force => true do |t|
    t.column "group_id",      :integer
    t.column "controller",    :string
    t.column "resource_id",   :integer
    t.column "resource_type", :string
    t.column "can_read",      :boolean
    t.column "can_write",     :boolean
    t.column "is_sticky",     :boolean
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "created_by",    :integer
    t.column "updated_by",    :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"
  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"

  create_table "users", :force => true do |t|
    t.column "login",            :string
    t.column "email",            :string
    t.column "crypted_password", :string,   :limit => 40
    t.column "salt",             :string,   :limit => 40
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "accessed_at",      :datetime
    t.column "created_by",       :integer
    t.column "updated_by",       :integer
    t.column "deleted",          :boolean,                :default => false
  end

end
